"""add edu programs

Revision ID: 100141c7ea11
Revises: 3c5c22b7ee64
Create Date: 2022-06-01 04:24:16.578054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Integer, String


# revision identifiers, used by Alembic.
revision = '100141c7ea11'
down_revision = '3c5c22b7ee64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('city', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('course', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('edu_program', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('ix_users_course'), 'users', ['course'], unique=False)
    op.create_index(op.f('ix_users_edu_program'), 'users', ['edu_program'], unique=False)

    edu_programs = table('edu_programs',
                         column('id', Integer),
                         column('name', String))

    op.bulk_insert(edu_programs, [
        {'name': 'Computer Science'},
        {'name': 'Software Engineering'},
        {'name': 'Big Data Analysis'},
        {'name': 'Media Technologies'},
        {'name': 'Mathematical and Computational science'},
        {'name': 'Telecommunication systems'},
        {'name': 'Smart Technologies'},
        {'name': 'Digital Journalism'},
        {'name': 'IT Management'},
        {'name': 'Cyber Security'},
        {'name': 'IT Entrepreneurship'},
        {'name': 'Digital public administration and services'},
        {'name': 'Industrial Internet of Things'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_edu_program'), table_name='users')
    op.drop_index(op.f('ix_users_course'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_column('users', 'edu_program')
    op.drop_column('users', 'course')
    op.drop_column('users', 'city')
    op.drop_table('edu_programs')
    # ### end Alembic commands ###
