"""add picture extension

Revision ID: f8690e5b3def
Revises: 4638327bfbbb
Create Date: 2022-07-13 14:30:52.167907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8690e5b3def'
down_revision = '4638327bfbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_pictures', sa.Column('extension', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_pictures', 'extension')
    # ### end Alembic commands ###
